server:
  port:

spring:
  application:
    name: filiere-service

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform:

  messages:
    basename: messages.messages
    encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone:
info:
  app:
    name: filiere-service
    version: 1.0.2
    description: Filiere & Regle De calcul Service
